<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <CdsiVersionFile>$(MSBuildThisFileDirectory)VERSION</CdsiVersionFile>
    <CdsiVersion>$([System.IO.File]::ReadAllText('$(CdsiVersionFile)').Trim())</CdsiVersion>
    <Version>$(CdsiVersion).0</Version>
    <AssemblyVersion>$(CdsiVersion).0.0</AssemblyVersion>
    <FileVersion>$(CdsiVersion).0.0</FileVersion>
    <InformationalVersion>$(CdsiVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Authors>CDSI Project</Authors>
    <Company>CDSI Project</Company>
    <Copyright>Copyright (c) 2026 CDSI Project</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/cdsi-project/Atlas</PackageProjectUrl>
    <RepositoryUrl>https://github.com/cdsi-project/Atlas.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
