<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CDSI.Agent.Application/CDSI.Agent.Application.csproj" />
    <ProjectReference Include="../CDSI.Agent.Infrastructure/CDSI.Agent.Infrastructure.csproj" />
  </ItemGroup>

</Project>